# Example composition of frontend, backend, nats, and postgres.
# You must specify MVNMON_WEBHOOK_SECRET and MVNMON_APP_ID,
# and generate a private key at configuration/private-key.der.
# See scripts/convert-private-key.sh for more information.

---
version: "3"

services:
  nats:
    image: nats-streaming
    command:
      - "--store"
      - "file"
      - "--dir"
      - "/data"
      - "--cluster_id"
      - "mvnmon"
    ports:
      - "4222:4222"
    volumes:
      - ./docker-compose-data/nats/:/data/

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PG_DATA: /data
    volumes:
      - ./docker-compose-data/postgres/:/data/
    healthcheck:
      test: "pg_isready -U user"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  db-migrate:
    image: mckdev/mvnmon:latest-snapshot
    build:
      context: .
      dockerfile: docker/Dockerfile
    command:
      - "db"
      - "migrate"
      - "/configuration.yaml"
    depends_on:
      - postgres
    environment:
      MVNMON_POSTGRES_SERVER: "postgres:5432"

  backend:
    image: mckdev/mvnmon:latest-snapshot-backend
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      args:
        VERSION: latest-snapshot
    ports:
      - "8082:8082"
      - "8083:8083"
    depends_on:
      - nats
      - postgres
      - db-migrate
    volumes:
      - ./configuration/private-key.der:/private-key.der
    environment:
      MVNMON_NATS_SERVER: "nats:4222"
      MVNMON_POSTGRES_SERVER: "postgres:5432"
      MVNMON_PRIVATE_KEY_FILE: "/private-key.der"
      MVNMON_APP_ID: "123456"

  frontend:
    image: mckdev/mvnmon:latest-snapshot-frontend
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        VERSION: latest-snapshot
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - nats
      - backend
    environment:
      MVNMON_NATS_SERVER: "nats:4222"
      MVNMON_WEBHOOK_SECRET: "secret"
