#!/bin/bash

set -ex

cd $(dirname $0)
cd ..

REPO=mckdev/mvnmon
VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)

# base
docker build . --file docker/Dockerfile --tag $REPO:$VERSION

# backend
docker build . \
  --file docker/Dockerfile.backend \
  --tag $REPO:$VERSION-backend \
  --build-arg VERSION=$VERSION

# frontend
docker build . \
  --file docker/Dockerfile.frontend \
  --tag $REPO:$VERSION-frontend \
  --build-arg VERSION=$VERSION