#!/bin/bash

set -ex

echo "PWD=$PWD"

cd $(dirname $0)
cd ../..

TAG_START=$(expr index "$IMAGE_NAME" :)
REPO=${IMAGE_NAME:0:TAG_START-1}
TAG=${IMAGE_NAME:TAG_START}

docker build . \
  --file $DOCKERFILE_PATH \
  --tag $IMAGE_NAME \

docker build . \
  --file $DOCKERFILE_PATH.frontend \
  --tag $IMAGE_NAME-frontend \
  --build-arg VERSION=$TAG

docker build . \
  --file $DOCKERFILE_PATH.backend \
  --tag $IMAGE_NAME-backend \
  --build-arg VERSION=$TAG