#!/bin/bash

set -ex

TAG_START=$(expr index "$IMAGE_NAME" :)
REPO=${IMAGE_NAME:0:TAG_START-1}
TAG=${IMAGE_NAME:TAG_START}

docker push $REPO:$TAG $REPO:$TAG-frontend $REPO:$TAG-backend

RELEASE_TAG_PATTERN='^[0-9.]+$'
if [[ "$TAG" =~ $RELEASE_TAG_PATTERN ]]
then
    # add 'latest' tags if a release was just built
    docker tag $REPO:$TAG $REPO:latest
    docker tag $REPO:$TAG-frontend $REPO:latest-frontend
    docker tag $REPO:$TAG-backend $REPO:latest-backend
    docker push $REPO:latest $REPO:latest-frontend $REPO:latest-backend
fi